version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-udemy
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'eazybank'
    volumes:
      - ./src/test/resources:/docker-entrypoint-initdb.d
      - ./src/Docker:/var/lib/mysql